# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy


# Language & Timezone
lang: en
timezone: America/Los_Angeles

# Site Metadata
title: Brianna Birkel
tagline: PhD Student at USC
description: >-
  Seismologist researching site amplification in the Los Angeles Basin.

url: "https://bcbirkel.github.io"
baseurl: ""

# Socials & Sidebar
github:
  username: bcbirkel

social:
  name: Brianna Birkel
  email: birkel@usc.edu
  links:
    - https://github.com/bcbirkel
    - https://scholar.google.com/citations?user=NABpEgEAAAAJ&hl=en

avatar: /assets/img/profile.jpg

# Theme mode (light, dark, or blank for toggle)
theme_mode: 

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme 

# Comments (optional — feel free to leave empty)
comments:
  provider:

# PWA settings
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# Pagination
paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Deployment
deploy:
  type: pages
